version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: my_mssql_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Contrasena12345678
  app:
    build:
      context: .
      dockerfile: olya_lab2/Dockerfile
    container_name: my_application
    ports:
      - "8080:8080"
    depends_on:
      - db